In [1]:
import sys
sys.path.append('d:/flagellar/code/core')
sys.path.append('/flagellar/code/core')
sys.path.append('/kaggle/input/my-flg-library/')
import flg_support as fls
import importlib
import numpy as np
import flg_diagnostics
import flg_numerics
import matplotlib.pyplot as plt
import flg_preprocess
importlib.reload(fls);
fls.profiling=False
sz = 5
sx = 100
sy = 100
t = 8

MainProcess
MainProcess


In [3]:
train_data = fls.load_all_train_data()[:10]
np.random.default_rng(seed=0).shuffle(train_data)
train_data = train_data
# plt.figure()
# plt.hist([t.voxel_spacing for t in train_data])
# train_data_extra = fls.load_all_extra_data()
# plt.figure()
# plt.hist([t.voxel_spacing for t in train_data_extra])

In [4]:
# importlib.reload(flg_diagnostics)
# importlib.reload(flg_numerics)
# flg_diagnostics.animate_labels(train_data, (sz,sx,sy), tile_num=t)

In [5]:
# %%time
# import glob
# files = glob.glob(fls.result_dir + '/many_abbr_full/Baseline*_0M*')
# models = [fls.dill_load(f) for f in files]
# preprocessor = models[0].trained_model.step1Labels.preprocessor
# #preprocessor.scale_moving_average = True
# #preprocessor.scale_also_moving_std = True
# flg_diagnostics.animate_labels(train_data, (sz,sx,sy), tile_num=t, preprocessor=preprocessor)

In [6]:
# %%time
# import glob
# files = glob.glob(fls.result_dir + '/many_abbr_full/Baseline*_0M*')
# models = [fls.dill_load(f) for f in files]
# preprocessor = models[0].trained_model.step1Labels.preprocessor
# preprocessor.scale_moving_average = True
# preprocessor.scale_also_moving_std = True
# preprocessor.blur_xy = 2
# flg_diagnostics.animate_labels(train_data, (sz,sx,sy), tile_num=t, preprocessor=preprocessor)

In [27]:
%%time
import glob
importlib.reload(flg_preprocess)
importlib.reload(flg_numerics)
importlib.reload(flg_diagnostics)
preprocessor = flg_preprocess.Preprocessor2()
#preprocessor.blur_xy = 0
#preprocessor.blur_xy_moving_std = 0
#preprocessor.clip_value = 4
flg_diagnostics.animate_labels(train_data[:5], (sz,sx,sy), tile_num=t, preprocessor=preprocessor)

[101 351 120]
!!!
[235 403 137]
!!!
[243 363 153]
!!!
[222 379 144]
!!!
[225 262 628]
!!!
[225 241 643]
!!!
[231 289 632]
!!!
[ 88 711 308]
!!!
[147 638 286]
!!!
CPU times: total: 2.64 s
Wall time: 2.41 s


In [28]:
%%time
import glob
importlib.reload(flg_preprocess)
importlib.reload(flg_numerics)
importlib.reload(flg_diagnostics)
preprocessor = flg_preprocess.Preprocessor2()
#preprocessor.blur_xy = 0
#preprocessor.blur_xy_moving_std = 0
#preprocessor.clip_value = 4
flg_diagnostics.animate_labels(train_data[:5], (sz,sx,sy), tile_num=t, preprocessor=preprocessor, collect_function = flg_numerics.collect_patches_xz_transposed)

!!!
(928, 960, 300)
[120 351 101]
!!!
(956, 924, 500)
[137 403 235]
[153 363 243]
[144 379 222]
[628 262 225]
[643 241 225]
[632 289 231]
!!!
(928, 960, 300)
[308 711  88]
!!!
(928, 960, 300)
[286 638 147]


d:\flagellar/code/core\flg_diagnostics.py:123: RuntimeWarning: Mean of empty slice
  mat = np.nanmean(mat,axis=1)[:,np.newaxis,:,:]


CPU times: total: 37.1 s
Wall time: 33.4 s


In [29]:
%%time
import glob
importlib.reload(flg_preprocess)
importlib.reload(flg_numerics)
importlib.reload(flg_diagnostics)
preprocessor = flg_preprocess.Preprocessor2()
#preprocessor.blur_xy = 0
#preprocessor.blur_xy_moving_std = 0
#preprocessor.clip_value = 4
flg_diagnostics.animate_labels(train_data[:5], (sz,sx,sy), tile_num=t, preprocessor=preprocessor, collect_function = flg_numerics.collect_patches_yz_transposed)

!!!
(959, 300, 928)
[351 101 120]
!!!
(924, 500, 956)
[403 235 137]
[363 243 153]
[379 222 144]
[262 225 628]
[241 225 643]
[289 231 632]
!!!
(960, 300, 928)
[711  88 308]
!!!
(960, 300, 928)
[638 147 286]


d:\flagellar/code/core\flg_diagnostics.py:123: RuntimeWarning: Mean of empty slice
  mat = np.nanmean(mat,axis=1)[:,np.newaxis,:,:]


CPU times: total: 37.7 s
Wall time: 34.1 s
